# Generated by Django 5.0.6 on 2024-05-29 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_main_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='main_author',
        ),
    ]
